# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bf193c2a3ba6a5fdb816bc04492d2bb1ed6066610f522d97a4b36bdc41f1c371f0af811e98f4d229f79227aeafff57718c9cde23d888399de057b52f51568d1

test:
  secret_key_base: b17817eb0534d43498e3ef12c6a0ac44f694604c94edd28597780743a1c13ed0bdbb33dd39dfcbe66e15f580a331d4db6a1627cf789f2ff7e0810ee4385d9736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
